[en_US]
v = "No leading or trailing whitespace"

[es_ES]
v = "Sin espacios en blanco al principio ni al final"

[ru_RU]
v = "Без пробелов в начале и конце"

[fr_FR]
v = "Pas de caractères blancs au début ou à la fin"
