[en_US]
v = "Are you sure you want to delete this account? This action cannot be undone"

[es_ES]
v = "¿Estás seguro de que deseas eliminar esta cuenta? Esta acción no se puede deshacer"

[ru_RU]
v = "Вы уверены, что хотите удалить этот аккаунт? Это действие нельзя отменить"

[fr_FR]
v = "Es-tu sûr de vouloir supprimer ce compte ? Cette action est irréversible"
